[toolchain]

[features]
resolution = true  #构建项目时会更严格地处理依赖项的版本解析
skip-lint = false  #是否跳过代码检查

[programs.localnet]
test_structure_array = "2yj1eyrGfhaveP39nHYpgbo5TK2jaP3uoBPtdyQgqdpW"

[programs.devnet]
test_structure_array = "2yj1eyrGfhaveP39nHYpgbo5TK2jaP3uoBPtdyQgqdpW"

[registry]
url = "https://api.apr.dev"

[provider]
#cluster = "Devnet"
#cluster = "https://devnet.helius-rpc.com/?api-key=ad4acf69-6c69-4edf-bccc-28397c4956e9"
cluster = "https://devnet-rpc.shyft.to?api_key=8VafiPaClmnwic-h"
#cluster = "https://rpc.ankr.com/solana_devnet/481cfd45dfcdeb78376bf1f445c5c7730f0863f320f4317507deca979078be78"
#cluster = "https://nd-358-368-151.p2pify.com/ddbc13f6219ffcae43d8ad1fba93db56"
#cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

#[test]
#startup_wait = 100000
