[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
test_structure_array = "FZhV3Aw5FFit8ro3QtDJaNJDoPYDeWybqnV7GkSLLqFn"

[programs.devnet]
test_structure_array = "FZhV3Aw5FFit8ro3QtDJaNJDoPYDeWybqnV7GkSLLqFn"

[registry]
url = "https://api.apr.dev"

[provider]
#cluster = "Devnet"
#cluster = "https://devnet.helius-rpc.com/?api-key=ad4acf69-6c69-4edf-bccc-28397c4956e9"
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
